
version: "3.8"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  order-api:
    build: ./order-api
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  coupon-service:
    build: ./coupon-service
    depends_on:
      - kafka
